### PR TITLE
Replace image code samples with text.

### PR DESCRIPTION
**Pull request by mbrukman**
This enables easy copy-pasting of sample code.

Also added code formatting for SQL keywords.

### CODE REVIEW

**Comment by bitti** [comment]
Why not delete the image on this occasion?

**Comment by mbrukman** [comment]
@bitti — the image appears to be also used on http://harelba.github.io/q/ but that needs to be updated as well, but I wasn't sure how to do that, so I left it alone.

If @harelba is OK with this as well, I'm happy to delete the image in the same commit.

**Comment by bitti** [comment]
@mbrukman the image might be screenshot from that site. On the site itself I see only text.

**Comment by mbrukman** [comment]
@bitti — good catch! I didn't even realize that was text on the main site and a screenshot here; I could have saved myself some time and copy-pasted from the site instead of re-creating the commands manually. 😄 

Removed the image from the PR in the latest updated commit.

**Comment by mcanlas** [comment]
Is this PR okay for merging?

**Comment by mbrukman** [comment]
@mcanlas -- yes, this PR is OK for merging, at least from my perspective.

**Comment by mbrukman** [comment]
@bitti, @mcanlas, @harelba – any thoughts/updates on this PR?

**Pull request merged**
