### PR TITLE
PEP8 compliance, syntax update to py2.6+ and indentation fixes

### PR DESCRIPTION
**Pull request by unode**
In addition to PEP8 compliance, the following changes were performed:

* `print >> handle` statements were replaced by handle.write() calls.
* `open()` was used instead of `file()`
* `except Exception, e` was replaced with `except Exception as e`
* exceptions were reworked to reduce duplicated code
* unused imports were removed
* indentation was fixed where relevant, including a few occasions of spaces not multiple of 4

### CODE REVIEW

**Comment by harelba** [comment]
@Unode Thanks! I'll take a deeper look during the weekend and merge it.

**Comment by cclauss** [comment]
Is this already fixed in master?

**Comment by harelba** [comment]
no, it hasn't actually.

**Comment by unode** [comment]
This is 2 years old, quite a few conflicts and changes since.
Back then py2.6+ was still a reasonable target, now Py3+ is a better choice. 
Feel free to cherry pick whatever still applies.

**Pull request closed without merging**
