### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
These modifications are compatible with both Python 2 and Python 3.

### CODE REVIEW

**Comment by harelba** [comment]
same here, thanks a lot, i'll merge it

**Comment by harelba** [comment]
btw, the main concern i have about moving to python3 is whether it will require modifying my (not good) packaging flow. But i guess it's time to move forward on this.

**Comment by cclauss** [comment]
With a codebase that supports both, there can be experimentation to ensure that the port is complete and that the Python 3 packaging works as well as the Python 3 version.

**Comment by harelba** [comment]
yeah, i agree, thanks for adding the python 3 tests in travis.

**Comment by cclauss** [comment]
My advise is don’t do it on a separate branch.  The big bang approach is rarely successful on larger codebases.  The goal is a single codebase that supports both Python 2 and Python 3 so step 1 is to add Python 3 to your continuous integration in __allow_failures__ mode.  Step 2 is to add this PR because it should not break compatibility with Python 2.  Use the CI and your own testing to make sure that is the case.  Step 3 is to make small changes to the encoding logic and make sure that each change does not break compatibility with Python 2.  In the end, you will have a codebase that you can flip back and forth between Python 2 and Python 3 to ensure that all functionality is equivalent.  Incrementalism is the key — Small changes with testing on Python 2 after each change.  Only after you are 100% satisfied that all functionality is equivalent on Python 2 and Python 3 should consider dropping support for legacy Python.

**Comment by cclauss** [comment]
If Facebook can make a codebase that works in both Python 2 and Python 3 than you can too...  https://talkpython.fm/episodes/show/185/creating-a-python-3-culture-at-facebook

**Comment by bitti** [comment]
Yes long living side branches are seldom a good idea. Integrate as early as possible. At least there should be no hindrance to merge these changes since they are Python 2 compatible.

**Comment by cclauss** [comment]
Done better elsewhere.

**Pull request closed without merging**
