### PR TITLE
Fix missing leading zero

### PR DESCRIPTION
**Pull request by d10xa**
```
echo $'01\n001\n0001' | python bin/q -c 1 "select * from -"
```

before:

```
1
1
1
```

after:

```
01
001
0001
```

### CODE REVIEW

**Comment by bitti** [comment]
Please not. We already have the option `--as-text` to achieve that purpose without breaking expectations in the standard case.

**Comment by d10xa** [comment]
This behavior is very dangerous! It is losing data by default. That do you think about making new switch`--allow-numbers-with-leading-zeroes`?

**Comment by bitti** [comment]
If that is your problem you're not solving it, because you're also loosing trailing zeros like in `1.000` or the `e` in `1e4`. `q` is doing implicit type conversions to make the common case easier and for special cases you've the `--as-text` option.

**Comment by d10xa** [comment]
1.000 is number. 0001 is identifier. It is not common case to have such numbers in database

**Comment by bitti** [comment]
For your usecase that might be the case, for others 0001 is a perfectly fine number. If you can't use `--as-text` because you need the type conversions for some columns but not for others, I would suggest appending a line to your input to trigger certain string conversions (and filtering it out via the where clause if necessary). E.g.

```
a	b	c	d
21	001	1.0	text1
25	002	1.2e1	text2
123	011	.1	text3
1	x	1.0	x
```

`1` would indicate integer, `x` text and `1.0` floats. That appending can be done without modifying the original file, that's what `cat` is for.

**Comment by d10xa** [comment]
@bitti ```q -H -t --as-text "select *, cast(b as number) as b_int from -"``` Does this look like a solution to your case?
it is better to do so as necessary than to sacrifice the safety of casting

**Comment by harelba** [comment]
I believe that a more robust solution would be to provide a way to override the type inference manually through the command line (e.g. `--column-type-overrides c2=text`). This is something that can help in several other cases as well.

**Pull request closed without merging**
